<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>custom_msg_interfaces</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="3578283292@qq.com">atguigu</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>std_msgs</depend>
  <depend>builtin_interfaces</depend>

  <!-- 构建工具依赖：提供 ROS 2 接口代码生成器 -->
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <!-- 运行时依赖：提供运行时使用生成接口所需的支持 -->
  <exec_depend>rosidl_default_runtime</exec_depend>

  <!-- 声明当前功能包属于 ROS 2 接口包组 -->
  <member_of_group>rosidl_interface_packages</member_of_group>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
